---
# tasks file for ansible_tomcat_roles
#- name: Download Tomcat8 from tomcat.apache.org
#  hosts: tomcat_server
    #  vars:
    #    download_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
# tasks:
   - name: Download Open JDK
     become: yes
     yum:
      name: java-1.8.0-openjdk
      update_cache: yes
      state: present

   - name: validate if Java is availble
     shell:
      java -version
   
   - name: check the vault content
     become: yes
     shell: |
       pwd
       ls -ltrh
       echo "{{user}}" > ./user.txt

   - name: Create the group
     become: yes
     group:
      name: "{{group}}"
      state: present
   - name: Create the user
     become: yes
     user:
        name: "{{user}}"
        state: present
   - name: Create a Directory /opt/tomcat8
     become: yes
     file:
       path: /opt/tomcat8
       state: directory
       mode: 0755
       owner: "{{user}}"
       group: "{{group}}"
   - name: Download Tomcat using unarchive
     become: yes
     unarchive:
       src: "{{download_url}}"
       dest: /opt/tomcat8
       mode: 0755
       remote_src: yes
       group: "{{group}}"
       owner: "{{user}}"

#   - name: Move files to the /opt/tomcat8 directory
#     become: yes
#     become_user: "{{user}}"
#     shell: "mv /opt/tomcat8/apache*/* /opt/tomcat8"
   - name: Creating a service file to run tomcat as a service using jinja template
     become: yes
     template:
      src: ../templates/index.j2
      dest: /etc/systemd/system/tomcat.service
   - name: Reload the SystemD to re-read configurations
     become: yes
     systemd:
        daemon-reload: yes
   - name: Remove the existing war file
     shell: rm -rf /opt/tomcat8/webapps/hello-world-maven.war 
   - name: Copy war files to tomcat
     become: yes
     copy:
       src: /var/lib/jenkins/workspace/jenkins-ansible-roles-cicd/target/hello-world-maven.war
       dest: /opt/tomcat8/apache-tomcat-8.5.84/webapps/
       owner: tomcat
       group: tomcat
       mode: 0644
   - name: Enable the tomcat service and start
     become: yes
     systemd:
        name: tomcat
        enabled: yes
        state: started
