---
- name: Playing with Ansible and Git
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: just execute a ls -lrt command
      shell: echo "hello world" >> abc
        #    register: output
  tasks:
    - name: Stop Apache tomcat service
      shell: service tomcat stop >> stop
    - name: Remove the existing war file
      shell: rm -rf /usr/share/tomcat/webapps/hello-world-maven.war 
    - name: Copy war files to tomcat
      copy:
        src: /var/lib/jenkins/workspace/Jenkins-CICD-Mygithub/target/hello-world-maven.war
        dest: /usr/share/tomcat/webapps/
        owner: tomcat
        group: tomcat
        mode: 0644
    - name: Start the Apache tomcat service
      shell: service tomcat start >> start 
